uint64 mp_id
string system_id

bool set_pose_bool
geometry_msgs/Vector3 set_pose

int64 add_observation_kf_id
int64 add_observation_vector_idx

int64 erase_observation_kf_id

bool set_bad_flag

int64 replace_id

bool increase_visibility_bool
int32 increase_visibility_n

bool increase_found_bool
int32 increase_found_n

bool compute_distinctive_descriptors

bool update_normal_and_depth

bool set_normal_vector_bool
geometry_msgs/Vector3 set_normal_vector

int64 update_map_id


